hashicorp/go-metrics

- prometheus.go
This is necessary when using hashicorp/raft on a machine whose hostname
contains dashes, like the travis build nodes.
> prometheus: replace not allowed character - with _ in metric names

- inmem.go
- inmem_test.go
I frequently find it necessary to keep track of when the last sample was added in an `IntervalMetric`. This PR adds a `LastUpdated` field to `AggregateSample` and is updated whenever `Ingest()` is called.
```go
s := im.Samples["foo.bar"]
rate := (s.Max - s.Min)/(s.LastUpdated.Sub(im.Interval).Seconds())
```
> add LastUpdated field to AggregateSample

- inmem.go
The code cleanup commit in b79a89c breaks the unit tests.  In particular rateDenom becomes zero if nanoseconds are not used for the calculation causing the Rate to become +Inf.  This may effect non-test code as well.
> Revert commit b79a89c to fix tests

- README.md
Annotate code sections as being Go, to get syntax highlighting.
> Use markdown code formating

- inmem.go
- inmem_test.go
- sink.go
- sink_test.go
- statsd.go
- statsd_test.go
- statsite.go
- statsite_test.go
The `NewMetricSinkFromURL` function allows a single string input to
configure any of the supported sink backends. The various pieces of the
URL are interpreted on a per-sink basis, and the generic `MetricSink`
interface is returned.
This is convenient for downstream users of go-metrics that want to
expose sink-agnostic configuration options, but for whom a more
complicated (e.g. HCL-based) config language is too heavy.
Currently the statsd, statsite, and inmem sinks are supported. Support
for the remaining sinks can be added as a follow up.
> Introduce unified URL-based sink factory function

- circonus/circonus.go
- circonus/circonus_test.go
- datadog/dogstatsd.go
- datadog/dogstatsd_test.go
- inmem.go
- inmem_endpoint.go
- inmem_endpoint_test.go
- inmem_signal.go
- inmem_test.go
- metrics.go
- metrics_test.go
- prometheus/prometheus.go
- sink.go
- sink_test.go
- start.go
- start_test.go
- statsd.go
- statsd_test.go
- statsite.go
- statsite_test.go
This adds new global functions for submitting metrics with key/value labels, as well as an endpoint function for displaying metrics from the most recent finished interval. Also modifies existing sinks to handle tagged metrics where applicable.
The endpoint's output looks like this when serialized to json:
```json
{
"Timestamp": "2017-08-02 01:06:00 -0700 PDT",
"Gauges": [
{
"Name": "consul.consul.session_ttl.active",
"Value": 0,
"Labels": {}
},
{
"Name": "consul.runtime.alloc_bytes",
"Value": 4228152,
"Labels": {}
}
],
"Points": [],
"Counters": [
{
"Name": "consul.consul.catalog.service.query",
"Count": 3,
"Sum": 3,
"Min": 1,
"Max": 1,
"Mean": 1,
"Stddev": 0,
"Labels": {
"service": "consul"
}
}
],
"Samples": [
{
"Name": "consul.serf.queue.Query",
"Count": 20,
"Sum": 0,
"Min": 0,
"Max": 0, …
```
> Add support for labeled metrics

- prometheus/prometheus.go
It is possible to create a naming collision with tagged metrics. Using the full key to store prevents this. The full key (named hash in the code) is already used to check for the existence of a previous key. 
Other considerations- it might be better to use a true hash function when creating the full key, rather than just string concatenation. This could be fixed up in a different PR though.
> Fix naming collision

- prometheus/prometheus.go
This PR changes the Sink to expire metrics after a configurable
duration. Before this change, ephemeral metrics would be tracked and
emitted forever. Not only does this emit undesirable metrics, it is a
memory leak.
> Handle ephemeral metrics

- inmem.go
`InmemSink.Data` return pointer to current interval (alongside with others)
`InmemSink.getExistingInterval` also return current interval.
Client can write to it while read 'current' interval from intervals returned by `InmemSink.Data()`
We need create copy for current interval.
> Fix race inmem

- README.md
- metrics.go
- metrics_test.go
- start.go
- start_test.go
This will allow for a more elegant solution to
https://github.com/hashicorp/consul/pull/4042
TODO:
> Allow filtering metrics using labels

- prometheus/prometheus.go
They are considered as an illegal character in prometheus text-format in metrics_name
Example file
```
TEST[promtheus]$ cat test.txt 
vault_audit_file/_log_request{quantile="0.5"} NaN
vault_audit_file/_log_request{quantile="0.9"} NaN
vault_audit_file/_log_request{quantile="0.99"} NaN
vault_audit_file/_log_request_sum 1.7049709558486938
vault_audit_file/_log_request_count 1
TEST[promtheus]$ cat test.txt | ./promtool check metrics
error while linting: text format parsing error in line 1: invalid metric name in comment
TEST[promtheus]$ cat test.txt | sed 's#/#_#g' | ./promtool check metrics && echo $?
0
```
> Add forward-slash as illegal character in prometheus

- start_test.go
```
+ go test -buildmode pie -compiler gc -ldflags '-extldflags '\''-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\'''
./start_test.go:56: T.Fatalf format %s has arg got of wrong type float32
./start_test.go:85: T.Fatalf format %s has arg got of wrong type float32
./start_test.go:127: T.Fatalf format %s has arg got of wrong type float32
FAIL	github.com/armon/go-metrics [build failed]
```
> Fix T.Fatalf has arg got of wrong type

- inmem_endpoint.go
- inmem_endpoint_test.go
method was not using the intervals returned by `Data()`
also, `Data()` documents that read locks are necessary
added documenting test and fix.
resolves #90
> added test/fix for race condition in DisplayMetrics

- inmem.go
- inmem_endpoint.go
- inmem_endpoint_test.go
- metrics.go
- metrics_test.go
there was another race condition in DisplayMetrics. `AggregateSample` wasn't deep-copied on `SampledValue` assignment, so that a lock on the parent `SampledValue` didn't protect the child `AggregateSample`. this meant that `Ingest` could write while `DisplayMetrics` was being called. 
I added to tests that document this with `-race`, then modified the copy code in `Data()` to use the new deep copy.
There is another issue in `Metrics`, where the array backing the passed `labels` slice was potentially being modified. In addition to potentially surprising users of this method, it also presents an opportunity for race conditions when a `SetGaugeWithLabels` calls rewrites the backing array while a `DisplayMetrics` call is reading it. There are two tests: the first was to verify and protect the …
> test and fix for another race condition in DisplayMetrics

- go.mod
- prometheus/prometheus.go
- prometheus/prometheus_test.go
Hello
In our environment we have stringent security needs.
Prometheus can not pull events from the services.
We allow only opposite connection from out backend server to 3rd party prometheus server.
We implemented this patch to push events to Prometheus push server.
Thanks and best regards,
Yuli
> Add prometheus pushserver support

- inmem.go
Addresses #103 
- Have in-mem `flattenKey` ops first `join` the slice elements together, *then* do a single `replace`, rather than a `replace` on every op of homebrew version of `join`
- Make the space replacer a `var` for `InMem`, rather than instantiating for every `flattenKey` call
Signed-off-by: Andrew Moore <andrew.s.moore@uber.com>
> clean up and enhance perf of inmem key flatten

- metrics.go
insert() in metrics.go is currently modifying the input slice.
Since this method is only ever used to prepend a value to the beginning of a slice,
changing the implementation to a new method insertAtBeginning() that does not modify
the input slice.
Signed-off-by: Ryan Turner <turner@uber.com>
Closes #101
> Fix insert() to not modify input slice

- prometheus/prometheus.go
When under heavy load, pprof showed that the bulk of contention in Vault with a Prometheus metrics sink was on the sink's mutex.  This makes sense, as all metric updates have to go through the same lock.  When there's a lot of metric traffic typically it's the same metrics that are getting updated over and over again, meaning the typical case is that the maps are going to be read from rather than written to.  This makes them a good candidate for sync.Map.
> Use sync.Map instead of a mutex for prometheus sink's metric maps

- prometheus/prometheus_test.go
So that the tests will run. It looks like this was merged in https://github.com/armon/go-metrics/pull/79/files#r480251321
> Fix syntax error and duplicate import

- datadog/dogstatsd_test.go
Fixes the datadog tests for the new expected value. The upgrade of github.com/DataDog/datadog-go in #100 caused the value of gauge metrics to change.
> Fix datadog tests

- start.go
This should make it easier to test code that uses go-metrics. In tests the code can be passed a different instance of Metrics, and in production code paths it can use the global Metrics returned from Default().
Without this change patching the global can cause flaky tests when other tests attempt to emit metrics to the global metrics instance.
An example of this can be see in https://github.com/hashicorp/consul/pull/8679 which uses this change to fix a flaky test.
Prior art: https://pkg.go.dev/github.com/hashicorp/go-hclog?tab=doc#Default
cc @armon @banks
> Expose the global default metrics

- prometheus/prometheus.go
- prometheus/prometheus_test.go
This PR introduces structs for Gauge, Summary, and Counter Definitions that can be provided to the `PrometheusSink` via its `PrometheusOpts`. The `PrometheusSink` will uses these definition slices to declare metrics when the process starts, and marks them internally to _not_ be deleted when their last-updated time passes the configured expiry. Instead, if `canDelete` is `false`, the PrometheusSink expires the metric by setting its value to NaN. When metrics aren't defined, they should behave as they always have before this PR. 
Allowing go-metrics users to define static metrics in prometheus lets us resolve a [long-requested](https://github.com/hashicorp/consul/issues/8590) [pain](https://github.com/hashicorp/consul/issues/8181) [point](https://github.com/hashicorp/consul/issues/5140) …
> Add {Gauge,Summary,Counter}Definitions to PrometheusOpts to define non-expiring metrics

- metrics.go
- metrics_test.go
When EnableRuntimeMetrics is true, New will leak a goroutine that collects stats periodically.  Export the method that does the stats collection so that those who are willing to call it themselves can avoid that goroutine leak.
> Export emitRuntimeStats to provide a workaround for goroutine leak.

- prometheus/prometheus.go
- prometheus/prometheus_test.go
When metrics are pre-registered with Help and without labels,
when issuing metrics with labels, the help was filled with
the key_name.
But prometheus client enforces help to be consistent accross
several elements, so, it can break at Runtime if a metric
has been declared without its labels and later issued this metric
with labels.
In order to fix this, we store the help declared at startup for
each key, so, when declaring a metric with some labels, we try
to re-used pre-declared help for the metric.
It should fix the issue that appeared with Consul 1.9.x and
fix https://github.com/hashicorp/consul/issues/9471
> Use the same Help for metrics with and without labels

- prometheus/prometheus.go
- prometheus/prometheus_test.go
#120 did excellent work to allow go-metrics consumers like Consul to define important metrics explicitly so they would not expire if they are not updated. The primary motivation was around ensuring we always provide metric summaries and descriptions for the most important metrics even if they've not changed for a while which was achieved.
The `Expiration` option in go-metrics though was still acting on Summaries and Gauges - effectively resetting them to `NaN` after the expiry time. This was intentional per the PR and comment but has a few downsides:
1. Gauges are often used for things that don't change often but might be relevant to know, for example the size of a queue. 
- In some implementations this is polled regularly to emit the gauge which worked fine provided the poll frequency is …
> Don't expire Prometheus metrics that have been explicitly defined

- inmem.go
We noticed some Consul tests deadlock and timeout when run with the race detector ([example](https://app.circleci.com/pipelines/github/hashicorp/consul/18113/workflows/d9d32c2f-9adb-4171-8957-734f50786d70/jobs/358395/tests)). I tracked down the problem to this line in `InmemSink.Data`.
In 1d3de9f7002ebf98cf5c2a86cd03b0dbf1f8e885 there was a change made to fix some data races in this method. It looks like the `RWMutex` field was missed, possibly because the issue isn't a data race itself, so isn't reported by the race detector.
`RWMutex` are not safe for copying, so we need to create a new instance on the copy of `IntervalMetrics`.
Before this change I was able to pretty reliable cause the test to deadlock in under 200 runs. After this change the test no longer deadlocks after 1000+ runs. …
> InmemSink: create a new RWMutex , because they are not safe to copy

- inmem.go
- inmem_endpoint.go
- inmem_endpoint_test.go
Related to one of the items in https://github.com/hashicorp/consul/issues/10320
We use the `InMemSink` to capture metrics for the debug archive, but the previous implementation resulted in us missing a lot of metrics because only 1/3 of the intervals were captured. Attempting to request the metrics at each interval is a challenge (maybe impossible), so instead this PR adds for an HTTP handler that sends metrics each time an interval completes.
> inmem: allow streaming of metrics as intervals complete

- inmem.go
- metrics.go
- prometheus/prometheus.go
- sink.go
#132 Added a new `Shutdown` method that solves a specific problem with short-lived processes.
Unfortunately since it added a new method to a public interface it broke backwards compatibility for other users of this library. We retracted the release v0.3.11 in #134.
Technically this library is still "zerover" since it's not yet made it to the 1.0.0 milestone and likely never will, but it is used widely in HashiCorp tools so it's preferable not to break downstream builds!
This PR moves the new `Shutdown` method into a separate interface that can be optionally implemented by Sinks. I also remove all the no-op implementations for built-in Sinks since they are not longer necessary.
@ggambetti would love to know if this will cause any issues for you? I think it should be compatible and tests …
> Refactor Shutdown into a separate interface to revert breaking change.

- README.md
- circonus/circonus.go
- circonus/circonus_test.go
- datadog/dogstatsd.go
- datadog/dogstatsd_test.go
- go.mod
- prometheus/prometheus.go
- prometheus/prometheus_test.go
When trying to `go get github.com/hashicorp/go-metrics`
This should fix it so it's possible to do above and not get:
```
go: downloading github.com/hashicorp/go-metrics v0.4.1
go: github.com/hashicorp/go-metrics@v0.4.1: parsing go.mod:
module declares its path as: github.com/armon/go-metrics
but was required as: github.com/hashicorp/go-metrics
```
> fix: package name and other moved repos

- circonus/circonus.go
- datadog/dogstatsd.go
- inmem.go
- inmem_endpoint.go
- inmem_signal.go
- metrics.go
- metrics_test.go
- prometheus/prometheus.go
- prometheus/prometheus_test.go
- sink.go
- sink_test.go
- start.go
- start_test.go
- statsd.go
- statsd_test.go
- statsite.go
- statsite_test.go
This adds a new API to send and store gauge metrics as float64s. Previously, they were being stored as float32s which isn't enough precision for storing unix timestamps. 
Related issue: https://github.com/hashicorp/vault/issues/19594 and https://github.com/hashicorp/go-metrics/issues/150
> Add GaugeFloat64 API

- datadog/dogstatsd.go
- datadog/dogstatsd_test.go
Fixes: #154 
If using the Fanout sink and including the dogstatsd sink, any sinks sent the metric AFTER dogstatsd could see invalid metric names. This was due to some inadvertent modifications to the original metric key. The new implementation ensure that when modifying the orignial metric key, a new backing array is used and will have key parts copied into it instead of changing elements in the original metric key.
> Prevent dogstatsd sink from clobbering the metric key for other sinks

- circonus/circonus.go
- circonus/circonus_test.go
Add PrecisionGauge to Circonus
> Add PrecisionGauge to Circonus

- const_js.go
- const_unix.go
This is necessary for users of this library who might be building with the WASM target.
> Add placeholder constant for JS

- prometheus/prometheus.go
- prometheus/prometheus_test.go
The Prometheus [Counter.Add()](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#Counter) method panics if the value being added is negative. Even if care is taken by consumers to never pass a negative value the panic could still happen due to float conversion or overflow.
This change prevents go-metrics from causing consumers to crash.
A panic like this has been reported in https://github.com/hashicorp/nomad/issues/15861, but, as far as I can tell, Nomad only calls `IncrCounter` and `IncrCounterWithLabels` using positive values.
> prometheus: prevent panic when incrmenting counter

- README.md
- compat/armon.go
- compat/circonus/armon.go
- compat/circonus/hashicorp.go
- compat/datadog/armon.go
- compat/datadog/hashicorp.go
- compat/hashicorp.go
- compat/prometheus/armon.go
- compat/prometheus/hashicorp.go
- go.mod
- go.sum
Introduce the backwards compatibility layer with armon/go-metrics.
The `compat` package (and its sub-packages) are API compatible with `armon/go-metrics@v0.4.1` or `hashicorp/go-metrics@v0.5.0`. The underlying metrics module will be selected for all consumers of the `compat` package by utilizing Go build tags.
* `armonmetrics` - Using this tag will cause metrics to be emitted via `armon/go-metrics`
* `hashicorpmetrics` - Using this tag will cause metrics to be emitted via `hashicorp/go-metrics`
If no build tag is specified the default behavior will be to use `armon/go-metrics` (however this behavior will be scheduled to change in 6 months).
The intention is that libraries will be updated to consume the `compat` package and then applications/services that produce the final binaries can use …
> Introduce `compat` package to ease migration from the old armon/go-metrice module name to the current hashicorp/go-metrics name

- .github/dependabot.yaml
- .github/workflows/build-test.yml
- CHANGELOG.md
- As per the memo: https://go.hashi.co/memo/eng-004,
Enabling the dependabot for identifying and updating the security and version updates in the repositories rather handling it manually.
- Adding the CHANGELOG.md file to maintain standardisation across OSS core libraries
- Updated build-test.yml workflow in order to test and generate code coverage report and uploading the same in artifacts for further use.
> IND-3830 enabling dependabot, changelog addition
